---
- name: Add Config file
  hosts: ex-nginx.lab.local
  become: yes
  tasks:
    - name: Copy Config template
      ansible.builtin.template:
        src: templates/k8s-ingress.conf.j2
        dest: /etc/nginx/conf.d/k8s-ingress.conf
    
    - name: Validate nginx config
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded