    Listen 80
    PidFile /run/httpd/httpd.pid
    DocumentRoot "/var/www/webstore"
    DirectoryIndex index.php

    LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    LoadModule env_module modules/mod_env.so

    User apache
    Group apache

    <Directory "/var/www/webstore">
        Require all granted
    </Directory>

    <FilesMatch \.php$>
       SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog /dev/stderr
    SetEnv APACHE_PORT ${APACHE_PORT}