# /group_vars/freeipa.yml
# Domain settings
ipaserver_domain: lab.local
ipaserver_realm: LAB.LOCAL
ipaserver_hostname: freeipa.lab.local

# DNS
ipaserver_setup_dns: yes
ipaserver_auto_forwarders: yes
ipaserver_no_dnssec_validation: yes
ipaserver_forwarders:
  - 8.8.8.8
  - 1.1.1.1

***REMOVED*** (Inject from AWS Secrets)
ipaadmin_password: "{{ lookup('env', 'IPA_ADMIN_PASSWORD') }}"
ipadm_password: "{{ lookup('env', 'IPA_DM_PASSWORD') }}"
freeipa_alias: freeipa

freeipa_firewall_services:
  - freeipa-ldap
  - freeipa-ldaps
  - freeipa-replication
  - dns
  - kerberos
  - http
  - https