apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared
  labels:
    type: nfs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/k8s-data
    type: Directory
