---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared
  labels:
    type: nfs
    environment: prod
  annotations:
    description: "Shared NFS storage for prod environment"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.40.120
    path: /volume1/k8s-prod
