---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared
  labels:
    environment: prod
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "NAS Storage Refrence Mount point /mnt/k8s-data >> /volume1/k8s-prod on AsusStor"  
spec:
  capacity: 
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.40.120
    path: /volume1/k8s-prod
