---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-data
  namespace: apps
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "Permenant storage for Wordpress"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-retain
  resources:
    requests:
      storage: 35Gi
