---
- name: Install Important K8s Tools
  hosts: k8s_masters
  become: true
  tasks:
    - name: Install Helm
      ansible.builtin.dnf:
        name: helm
        state: present

    - name: Install Calico Ctl
      ansible.builtin.get_url:
        url: https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64
        dest: /usr/local/bin/calicoctl
        mode: '0755'
