# ansible/dev/requirements.yml
collections:
  - name: community.general
  - name: community.hashi_vault
  - name: freeipa.ansible_freeipa
  - name: prometheus.prometheus
  - name: kubernetes.core
  - name: ansible.posix
  - name: grafana.grafana    # manages Grafana on bare Linux
  - name: community.nginx    # or just manage via community.general