# /playbooks/ansible_setup.yml
---
- name: Install Common Packages
  hosts: local
  become: yes
  tasks:
    - name: Install Packages
      ansible.builtin.dnf:
        name: "{{ initial_packages }}"
        state: present

    - name: Install Ansible Collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r /opt/ansible/infrastructure/ansible/dev/requirements.yml --upgrade
      changed_when: true
