# /playbooks/freeipa_setup.yml
---
- name: Install FreeIPA Server
  hosts: freeipa
  become: yes

  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ ipaserver_hostname }}"

    - name: Add hostname to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipaserver_hostname }} {{ freeipa_alias }}"
        state: present

    - name: Start and enable firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Allow FreeIPA Firewall Services
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      loop: "{{ freeipa_firewall_services }}"

    - name: Install FreeIPA server packages
      ansible.builtin.dnf:
        name:
          - ipa-server
          - ipa-server-dns
        state: present

    - name: Check if FreeIPA is already installed
      ansible.builtin.stat:
        path: /etc/ipa/default.conf
      register: ipa_installed

    - name: Install FreeIPA Server
      ansible.builtin.command:
        cmd: >
          ipa-server-install
          --hostname={{ ipaserver_hostname }}
          --domain={{ ipaserver_domain }}
          --realm={{ ipaserver_realm }}
          --ds-password={{ ipadm_password }}
          --admin-password={{ ipaadmin_password }}
          --setup-dns
          --forwarder=8.8.8.8
          --forwarder=1.1.1.1
          --ntp-server=pool.ntp.org
          --unattended
      when: not ipa_installed.stat.exists