---
- name: Install FreeIPA Server
  hosts: freeipa
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      vars:
        ipaserver_domain: lab.local
        ipaserver_realm: LAB.LOCAL
        ipaserver_admin_password: "{{ vault_ipa_admin_password }}"
        ipaserver_ds_password: "{{ vault_ipa_ds_password }}"
        ipaserver_setup_dns: true
        ipaserver_auto_forwarders: true