---
- name: Test Ansible
  hosts: all
  become: yes
  tasks:
    - name: Get Hostname
      ansible.builtin.command:
        cmd: hostnamectl
      register: hostname_output

    - name: Display Hostname
      ansible.builtin.debug:
        msg: "{{ hostname_output.stdout_lines }}"

