---
- name: Backup Jenkins Agent Keys to Vault
  hosts: jenkins_agents
  become: yes
  vars_prompt:
    - name: admin_user
      prompt: "Enter Vault Admin Username"
      private: no
    - name: admin_password
      prompt: "Enter Vault Admin Password"
      private: yes


  tasks:
    # --- VAULT AUTHENTICATION ---
    - name: Authenticate to Vault using userpass
      community.hashi_vault.vault_login:
        url: "{{ vault_server_url }}"
        auth_method: userpass
        username: "{{ admin_user }}"
        password: "{{ admin_password }}"
      register: vault_auth_result
      delegate_to: localhost

    # --- READ KEYS FROM AGENT ---
    - name: 01-Read SSH keys from Agent VM
      block:
        - name: 01a-Slurp private key
          slurp:
            src: "/var/lib/jenkins_agent/.ssh/id_rsa"
          register: agent_private_key

        - name: 01b-Slurp public key
          slurp:
            src: "/var/lib/jenkins_agent/.ssh/id_rsa.pub"
          register: agent_public_key

    # --- WRITE TO VAULT ---
    - name: 02-Write Keys to Vault KV
      community.hashi_vault.vault_kv2_write:
        url: "{{ vault_server_url }}"
        token: "{{ vault_auth_result.login.auth.client_token }}"
        engine_mount_point: "secret"
        path: "{{ jenkins_secret_path }}"
        data:
          private_key: "{{ agent_private_key.content | b64decode }}"
          public_key: "{{ agent_public_key.content | b64decode }}"
      delegate_to: localhost

    # # --- CLEANUP (OPTIONAL BUT RECOMMENDED) ---
    # - name: 03-Remove Private Key from Agent disk for security
    #   file:
    #     path: "/var/lib/jenkins_agent/.ssh/id_rsa"
    #     state: absent
    #   tags: cleanup

    # - name: Final Summary
    #   debug:
    #     msg: 
    #       - "✅ Keys successfully moved to Vault at {{ jenkins_secret_path }}"
    #       - "⚠️  Private key has been deleted from Agent VM disk."


## Later You will need to add the private key manually to the jenkins credintail secrets, u can retrieve it from vault when needed