---
- name: Configure Local Veeam Emergency User
  hosts: all
  become: true
  vars:

    # We remove "key='public_key'" from inside the lookup
    # And instead add "['public_key']" at the very end to extract the string.
    veeam_public_key: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/infra/veeam_emergency')['public_key'] }}"
# vault login -method=userpass username=admin1

    # The Server VLAN (Allows Veeam + Helper Appliances)
    allowed_subnet: "10.0.20.0/24"

  tasks:
    - name: Create the veeam_emergency
      user:
        name: veeam_emergency
        comment: "Local Emergency Backup User"
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Deploy SSH Public Key (Restricted to Subnet)
      authorized_key:
        user: veeam_emergency
        state: present
        key: "{{ veeam_public_key }}"
        # Only allow connections from the Server VLAN
        key_options: 'from="{{ allowed_subnet }}"'

    - name: Configure Sudoers (Passwordless Sudo)
      copy:
        dest: /etc/sudoers.d/veeam_emergency
        content: "veeam_emergency ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
        validate: 'visudo -cf %s'
