apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-config
  namespace: monitoring
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "loki"
    receivers:
      - name: "loki"
        loki:
          url: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
          streamLabels:
            job: "kube-events"
          layout:
            message: "{{ .Message }}"
            source: "{{ .Source.Component }}"
            reason: "{{ .Reason }}"
            object: "{{ .InvolvedObject.Kind }}/{{ .InvolvedObject.Name }}"
            namespace: "{{ .InvolvedObject.Namespace }}"
            type: "{{ .Type }}"
