##### Deploy Against LXC #####
## Create As config ansible/prod/playbooks/common/templates/chrony_lxc.conf

# Use public NTP servers from the pool.ntp.org project.
# The 'iburst' option allows for faster initial synchronization.

# 1. Your internal source (For consistency across the domain)
server freeipa.lab.local iburst prefer
# server 10.0.50.10 iburst # uncomment if dns down

# 2. Reliable secondary public sources (For redundancy)
pool 0.pool.ntp.org iburst
pool 1.pool.ntp.org iburst

# 3. Cloudflare
server time.cloudflare.com iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync # LXC has no RTC (hardware clock)

# Specify the directory of additional configuration files.
confdir /etc/chrony.conf.d

# Enable logging of system clock gains/losses.
logdir /var/log/chrony

# Stop bad estimates from upsetting the machine clock.
maxupdateskew 100.0
