---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-storage
  namespace: monitoring
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "Storage for monitoring tools"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-monitoring


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logging-storage
  namespace: logging
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "Storage for logging tools"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-logging


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-storage
  namespace: apps
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "Storage for applications"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-apps

  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testing-storage
  namespace: testing
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
  annotations:
    description: "Temporary storage for testing workloads"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-testing
