apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: etcd-backup
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEVjCCAr6gAwIBAgIRAMc6+vJQGpi4YFmrfB5gjEQwDQYJKoZIhvcNAQELBQAw
    NDESMBAGA1UECgwJTEFCLkxPQ0FMMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRo
    b3JpdHkwHhcNMjYwMzA2MjM1NTI5WhcNNDYwMzA2MjM1NTI5WjA0MRIwEAYDVQQK
    DAlMQUIuTE9DQUwxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIw
    DQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALaGGJ92Fj6sTblquVWr9op7jFPQ
    h/xsO9klTe7TJixvFKeSPsFj2e5dmF2Zn3LLNlId3bwzVQj8UW+3QAeZIUZ/GXaz
    qapGPUh+t/qvjHe00sHEPUHwQZC3St5ZQ0gcywykqlSJSbkn+MWvuGQGsVpZNtyL
    3iChTIJB0aJaA6ySCPg3fJVZvOObmymKdRIQRGCSmME8weE6VKmsVLdVp5X8tRgd
    lZI52HGkFXFJQTvggZ1szhPTtu67WWZIcNYEyBQUwO/lum87Jw1hog0VySSRUq1w
    CCeFYulokzDzPcft6bKoIOje620yhG+JOAzZhOXg8Q8p5C1652spiJ0nhoqV9L8h
    QSFwnr5Yc9JKtSWnUhmWnSnr5/RVcRqFugFJr7awoP93PhWEPgvyZ83h3A1J3Ckx
    jDlJFjMlELLNmrt1S/M1VBttYQvIKIsKipajglmlvygifypu6LskpgDaQbluAINY
    uzyAYUy1Y4lckqcM/955ukpVZ2CybgCNhR6pHQIDAQABo2MwYTAdBgNVHQ4EFgQU
    I+7/765bHbqhJsL8UJ0rAXR19KwwHwYDVR0jBBgwFoAUI+7/765bHbqhJsL8UJ0r
    AXR19KwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwDQYJKoZIhvcN
    AQELBQADggGBAFjEAyRzjxZFJ2dnEz6levbBNHS/0o5t3rG6D6BWGPqx4V9Yl80y
    3FsFlpM2iwCVdejcSYWAkPx9vRo+0PZSaS2C48uYJX6qHL9fZUs7GdNA1cMZipca
    0T74pyeSx+pbILglnuJ/6Os222TWccdSm+IHSF9wU4M4gRWk7RzaCjucpRRlgxIl
    0s0ovaHErlIg96Hh8xMuKz3rE/S3X0FtJGn8k3nI8CxljpfReUj2qJ8GmTa7iFJD
    rfweqYly5ylo3ZNickpAoHmx3p7yMbXiLHLNtwKmxHV45SP2Yl/Eb8+/VWVVzgR+
    wApvOBabhgYMlg9iJ2Dj3szEGJSDs9yFwR399XdZWnq5oMbA+p87QOz73T0eQq9g
    5kNHlPT6XV84h6jI3f6i+MqpkLb9Gd/KCbdf01Y7+v/tWWNjVmp52h//WemT3eiM
    QJvTosW0ItC6gHfComQkE7irbHQQy3P4bmfcitOq19AqtafJVuMFowL2x8lqDhqm
    kYvyj/QQQ/xcEg==
    -----END CERTIFICATE-----