apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  # vault-ca-secret already exists in monitoring namespace
  - statefulset.yaml
  - service.yaml
