---
- name: Enable SSH Password Authentication on VMs
  hosts: k8s_masters,k8s_workers
  become: yes
  tasks:
    - name: Enable PasswordAuthentication in cloud-init sshd config
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: 'PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
