# /group_vars/local.yml
initial_packages:
  - vim
  - git
  - curl
  - htop
  - unzip


ipaclient_domain: lab.local
ipaclient_realm: LAB.LOCAL
ipaclient_servers:
    - freeipa.lab.local
ipaadmin_principal: admin
ipaadmin_password: "{{ lookup('env', 'IPA_ADMIN_PASSWORD') }}"
ipaclient_mkhomedir: yes