ipa_host_groups:  
    - name: automation_group                                                                                   
      description: "All server hosts managed by Bot User"
      hosts: "{{ ipa_managed_hosts }}"

    - name: k8s_masters
      description: "Kubernetes master nodes"
      hosts:
        - k8s-master1.lab.local
        - k8s-master2.lab.local
        - k8s-master3.lab.local

    - name: k8s_workers
      description: "Kubernetes worker nodes"
      hosts:
        - k8s-worker1.lab.local
        - k8s-worker2.lab.local
        - k8s-worker3.lab.local

    - name: vault_cluster
      description: "HashiCorp Vault cluster"
      hosts:
        - vault1.lab.local
        - vault2.lab.local
        - vault3.lab.local

    - name: ansible_nodes
      description: "Ansible control nodes"
      hosts:
        - ansible.lab.local
    
    - name: runner_nodes
      description: "CI/CD runner nodes"
      hosts:
        - local-runner.lab.local

    - name: nginx_nodes
      description: "Nginx reverse proxy"
      hosts:
        - ex-nginx.lab.local

domain_bot_users:
    - name: super_bot                                                                                          
      first: Super
      last: Bot                                                                                              
      description: "Automation Bot User"      
      hostgroups:
        - automation_group
      options:
        - "!authenticate"


ipa_admin_users:

    - name: k8s_admin                                                                                          
      first: K8s
      last: Admin                                                                                              
      description: "K8s cluster admin"      
      hostgroups:
        - k8s_masters
        - k8s_workers

    - name: vault_admin
      first: Vault
      last: Admin
      description: "Vault cluster admin"
      hostgroups:
        - vault_cluster

    - name: nginx_admin
      first: Nginx
      last: Admin
      description: "Nginx admin"
      hostgroups:
        - nginx_nodes

    - name: ansible_admin
      first: Ansible
      last: Admin
      description: "Ansible node admin"
      hostgroups:
        - ansible_nodes

    - name: runner_admin
      first: Runner
      last: Admin
      description: "Runner node admin"
      hostgroups:
        - runner_nodes

default_admin_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63636137613538623464613331396432313532656365376330383862373662303135306536636363
          6135373264383265613863643131613763303264336430380a363033623061363437313339313536
          33386430636337373764633130643037623865623633306534363733316461313430313366373137
          3863383736303330360a653563393935346438336135333233623733656338363636303265643361
          6663

default_bot_user_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31376663356335363539373436326161313230333130663432373732346661613739653766373364
          3133303063336661343232333837366332373932373365370a643935626365376665393931346466
          32303862623234363834613264653062353533306235396561303164386463353131636236336364
          3461313365613364650a383532623861663862363665373838653137633464316365363638366536
          3631

# ansible-vault encrypt_string 'Put password' --name 'default_bot_user_password'