# DEV Environment Inventory
# All connections use root with pre-configured SSH key trust

# VMs (VLAN 60, 61, 64)
[freeipa]
freeipa.lab.local    ansible_user=root 
#ansible_host=10.0.60.10

[k8s_masters]
k8s-master1.lab.local 
#ansible_host=10.0.61.10
k8s-master2.lab.local 
#ansible_host=10.0.61.11
k8s-master3.lab.local 
#ansible_host=10.0.61.12

[k8s_workers]
k8s-worker1.lab.local 
#ansible_host=10.0.64.10
k8s-worker2.lab.local 
#ansible_host=10.0.64.11
k8s-worker3.lab.local 
#ansible_host=10.0.64.12

# LXCs (VLAN 62, 63, 65)
[vault_cluster]
vault1.lab.local 
#ansible_host=10.0.62.10
vault2.lab.local 
#ansible_host=10.0.62.11
vault3.lab.local 
#ansible_host=10.0.62.12

[ansible]
ansible.lab.local  ansible_connection=local
#ansible_host=10.0.63.10

[local_runners]
local-runner.lab.local 
#ansible_host=10.0.63.20

[nginx]
ex-nginx.lab.local 
#ansible_host=10.0.65.10

# Group definitions
[k8s:children]
k8s_masters
k8s_workers


[managed_hosts:children]
k8s_masters
k8s_workers
vault_cluster
ansible
local_runners
nginx


## In Invitory add 

[vms:children]
k8s_masters
k8s_workers
freeipa

[lxc:children]
vault_cluster
ansible
local_runners
nginx

[managed_hosts:vars]
ansible_user=super_bot
ansible_become=yes
ansible_become_method=sudo


[all:vars]
#ansible_user=super_bot
#ansible_become=yes
#ansible_become_method=sudo
#ansible_user=root
