---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: database
  labels:
    environment: dev
    app.kubernetes.io/managed-by: flux
    app: wordpress
  annotations:
    description: "Permenant storage for mariadb"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-retain
  resources:
    requests:
      storage: 15Gi
