---
- name: Configure Vault Raft Cluster
  hosts: vault
  become: yes

  tasks:
    - name: 1. Deploy Vault Configuration
      template:
        src: vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: vault
        group: vault
        mode: '0640'
      notify: Restart Vault

    - name: 2. Create Systemd Service Override (LimitMEMLOCK)
      # This is required for 'disable_mlock = false' to work.
      # It tells Linux: "Allow the Vault user to lock unlimited memory."
      file:
        path: /etc/systemd/system/vault.service.d
        state: directory

    - name: 3. Set LimitMEMLOCK infinity
      copy:
        dest: /etc/systemd/system/vault.service.d/override.conf
        content: |
          [Service]
          LimitMEMLOCK=infinity
      notify: Reload Systemd and Restart Vault

    - name: 4. Start and Enable Vault Service
      service:
        name: vault
        state: started
        enabled: yes

  handlers:
    - name: Restart Vault
      service:
        name: vault
        state: restarted

    - name: Reload Systemd and Restart Vault
      systemd:
        daemon_reload: yes
        name: vault
        state: restarted