---
- name: Setting up kubeconfig directory
  ansible.builtin.file:
    path: /opt/.kube
    state: directory
    mode: '0755'

- name: Copy Config File to /opt/.kube
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /opt/.kube/config
    remote_src: yes
    owner: k8s_admin
    group: k8s_admin
    mode: '0600'

- name: Set KUBECONFIG system-wide
  ansible.builtin.lineinfile:
    path: /etc/profile.d/kubernetes.sh
    line: 'export KUBECONFIG=/opt/.kube/config'
    create: yes
    mode: '0644'

- name: K8s Validation
  ansible.builtin.command:
    cmd: kubectl get nodes
  register: get_node_output

- name: Display validation
  ansible.builtin.debug:
    var: get_node_output.stdout_lines
