apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-pod
  namespace: kube-system
spec:
  replicas: 3
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccountName: remediation-sa
      priorityClassName: self-healing-critical
      containers:
        - name: remediation
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
