apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-pod
  namespace: kube-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: remediation-pod
  template:
    metadata:
      labels:
        app: remediation-pod
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      serviceAccountName: remediation-sa
      priorityClassName: self-healing-critical
      containers:
        - name: remediation
          image: ghcr.io/mohamedsabry-dev/remediation:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "/scripts/remediation.py"]
          volumeMounts:
            - name: script
              mountPath: /scripts
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: script
          configMap:
            name: remediation-script