apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: apps
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEVTCCAr2gAwIBAgIQXwrBTFKYD5xPiEzwWjcptDANBgkqhkiG9w0BAQsFADA0
    MRIwEAYDVQQKDAlMQUIuTE9DQUwxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhv
    cml0eTAeFw0yNjAzMDUxNDAzNTRaFw00NjAzMDUxNDAzNTRaMDQxEjAQBgNVBAoM
    CUxBQi5MT0NBTDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojAN
    BgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEApYszc5MsLTLFm/Id87pOFka+opbx
    bc3udb1rrH2ByRK59qyY9mQoqh92pdXsiwazsViXvE3HCjhDW2CUBMbKZRXnfDdn
    eIxXEKqqaHAqzDDghAMqsVf5bFFLZYa5gAV47nMCdaFcdCEfmwzvzIeE1kbWAY4D
    ciCsShYVIYTzFV7qcVdCZcuhaeN85gGaod0mPIH2eG/4lCn2QrJgrrKbTiZgzvfc
    WUsqwMQUoWAsl6JXHDKvfecfOr8Kg7NqxBd7aFs4r4WA80tum827fEMRo2JPsEr8
    bOCBzUgVIYtcWyuHxhiYae7AEzql4Hv/KsPdYPZzJFxG4okISlVoG1ZqgqZHI2R6
    rqs1xYnip/dsjCgFttGh5Xr6rdQfpfMgd9TQBdtwH81ip0J1QEXvkbd/IT83riKB
    S1qnSHvKd9TMrTKzc/1gIaFYwuJfEJ8y3a8/NDlXBuzqJNOXUHShew4hBIZJQvcg
    nsnGgl57yMSH+RCStO2lj0ZqYUJoiH1cXKIxAgMBAAGjYzBhMB0GA1UdDgQWBBQz
    0cyF3T/LcvIs7NVvahbmHMZ2wTAfBgNVHSMEGDAWgBQz0cyF3T/LcvIs7NVvahbm
    HMZ2wTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjANBgkqhkiG9w0B
    AQsFAAOCAYEAlruBFtSnrQSmsAgnHlxWu/pT3V1+GIQiZeDjau8YicMFAjzBZQcs
    jZgOklGd/TM9xasOVC/oEpgSP/zCh0Us3nnBUFFjwt9CR2+yVk79InJNtHx5PLJM
    MC81OVyWiovWFfYPMkuLiaUxbtS+p5SddP44ZDa5AaUkCeKSQHs3753fM4jC8N5P
    fya7QCzZ0FYF80vprlNtkhB0o8IdxwCHmLfObbrfK/iWqecizrjd+Q0f02Pqa6Nq
    XbWoxMGfQD0XF4RLs4KDWKSODfnzihpT6GJzIXgnOExhtoEhZgO81MHOsBR/cqmK
    8LVxXhB10pNy6a80A8UJZbDMX2InGB5/De1zktct4AN0V1mpo9vrA15ifkoeTxMk
    o7cIlgMG28YOj3tTlyirNHRU/H1M2w/YfTWrMxciskje538AAmRPc/+NQ5i/vbkf
    Ln24dOfIAnuu2hVlyreE+/d5L4JrhqaGTtukromjEh82d3lVRRoRT80a3HPMZuZS
    PoyDvoe9ds7u
    -----END CERTIFICATE-----
