apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager-sa
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/managed-by: flux
    environment: prod
