apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/managed-by: flux
    environment: prod
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      targetPort: web
    - name: mesh
      port: 9094
      targetPort: mesh
  selector:
    app: alertmanager
