apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mariadb
  namespace: database
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/managed-by: flux
    environment: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
