---
- name: Join hosts to FreeIPA domain
  hosts: all:!freeipa
  become: yes

  pre_tasks:
    - name: Add FreeIPA to /etc/hosts for DNS bootstrap
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "10.0.60.10 freeipa.lab.local freeipa"
        state: present
  roles:
    - role: freeipa.ansible_freeipa.ipaclient