# playbooks/freeipa_setup.yml
---
- name: Install FreeIPA Server
  hosts: freeipa
  become: yes

  vars:
    # FreeIPA Server Configuration
    ipaserver_domain: lab.local
    ipaserver_realm: LAB.LOCAL
    ipaserver_hostname: freeipa.lab.local

    # DNS Configuration
    ipaserver_setup_dns: yes
    ipaserver_auto_forwarders: yes
    ipaserver_no_dnssec_validation: yes
    ipaserver_forwarders:
      - 8.8.8.8
      - 1.1.1.1

    # Passwords (Injected from AWS Secrets via CI/CD)
    ipaadmin_password: "{{ lookup('env', 'IPA_ADMIN_PASSWORD') }}"
    ipadm_password: "{{ lookup('env', 'IPA_DM_PASSWORD') }}"
    freeipa_alias: freeipa

  pre_tasks:
    - name: Uninstall IPA client if present
      ansible.builtin.command:
        cmd: ipa-client-install --uninstall --unattended
      ignore_errors: yes
      changed_when: false

    - name: Disable cloud-init hosts management
      ansible.builtin.lineinfile:
        path: /etc/cloud/cloud.cfg
        regexp: 'manage_etc_hosts'
        line: "manage_etc_hosts: False"

    - name: Remove all existing freeipa entries from /etc/hosts
      ansible.builtin.shell: |
        sed -i '/freeipa/d' /etc/hosts
      changed_when: true

    - name: Add correct /etc/hosts entry for FreeIPA
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ipaserver_hostname }} {{ freeipa_alias }}"
        state: present

  roles:
    - role: freeipa.ansible_freeipa.ipaserver