- name: Setup Domain
  hosts: freeipa
  become: yes
  tasks:
    - name: Setup Host Groups
      freeipa.ansible_freeipa.ipahostgroup:
          ipaadmin_principal: "{{ ipaadmin_principal }}"
          ipaadmin_password: "{{ ipaadmin_password }}"
          name: automation_group
          description: "All server hosts managed by Bot User"
          host: "{{ ipa_managed_hosts }}"
          state: present
