name: "[DEV] Ansible Service Install"
on:
  push:
    branches:
      - dev
    paths:
      - 'ansible/dev/**'
      - '.github/workflows/dev-service_ansible.yml'

env:
  ENVIRONMENT: dev

jobs:
  deploy:
    name: "Deploy Ansible Service Install"
    runs-on: dev-local-runner

    steps:
      - name: Install Ansible
        run: |
          sudo ssh root@10.0.63.10 "dnf install -y ansible-core python3-pip"

      - name: Pull latest code
        run: |
          sudo ssh root@10.0.63.10 "cd /opt/ansible/infrastructure && git pull origin dev"

      - name: Run Ansible playbook
        run: |
          sudo ssh root@10.0.63.10 "cd /opt/ansible/infrastructure/ansible/dev && ansible-playbook -i inventory/inventory.ini playbooks/ansible_setup.yml"
