name: "[DEV] Freeipa VM"
on:
  push:
    branches:
      - main
    paths:
      - 'ansible/dev/**'
      - '.github/workflows/dev-freeipa-vm.yml'

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  ANSIBLE_INVENTORY: ansible/dev/inventory/inventory.ini
  ANSIBLE_PLAYBOOK: ansible/dev/playbooks/dev-freeipa-service.yml

jobs:
  install-freeipa-server:
    runs-on: dev-local-runner

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_PROD }}:role/GitHubActions-Infrastructure-${{ env.ENVIRONMENT }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Fetch freeipa Credentials
        run: |
          freeipa_ADMIN_PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id dev/freeipa/admin_password \
            --query SecretString --output text)
          echo "::add-mask::${freeipa_ADMIN_PASSWORD}"
          echo "freeipa_ADMIN_PASSWORD=${freeipa_ADMIN_PASSWORD}" >> $GITHUB_ENV

          freeipa_DS_PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id dev/freeipa/ds_password \
            --query SecretString --output text)
          echo "::add-mask::${freeipa_DS_PASSWORD}"
          echo "freeipa_DS_PASSWORD=${freeipa_DS_PASSWORD}" >> $GITHUB_ENV

      - name: Run FreeIPA Install Playbook
        run: |
          ssh root@10.0.63.10 "cd /opt/ansible/infrastructure && \
          ansible-playbook -i ${{ env.ANSIBLE_INVENTORY }} ${{ env.ANSIBLE_PLAYBOOK }} \
          -e ipaserver_admin_password=${{ env.freeipa_ADMIN_PASSWORD }} \
          -e ipaserver_ds_password=${{ env.freeipa_DS_PASSWORD }}"