name: "[DEV] Svc - Ansible Setup"
on:
  push:
    branches:
      - dev
    paths:
      - 'ansible/dev/**'
      - '.github/workflows/dev-svc-ansible-setup.yml'

env:
  ENVIRONMENT: dev

jobs:
  deploy:
    name: "Setup Ansible"
    runs-on: dev-local-runner
    if: ${{ vars.DEV_SVC_ANSIBLE_SETUP_LOCK != 'true' }}

    steps:
      - name: Install Ansible
        run: |
          ssh -o StrictHostKeyChecking=no root@10.0.63.10 "dnf install -y ansible-core python3-pip"

      - name: Pull latest code
        run: |
          ssh root@10.0.63.10 "cd /srv/repo && git pull origin dev"

      - name: Run Ansible playbook
        run: |
          ssh root@10.0.63.10 "cd /srv/repo/ansible/dev && ansible-playbook -i inventory/inventory.ini playbooks/ansible_setup.yml"
