name: "[DEV] FreeIPA Service Install"
on:
  push:
    branches:
      - dev
    paths:
      - 'ansible/dev/**'
      - '.github/workflows/dev-svc-freeipa-server-setup.yml'
permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev

jobs:
  deploy:
    name: "Deploy FreeIPA Service Install"
    runs-on: dev-local-runner
    if: ${{ vars.DEV_SVC_FREEIPA_SETUP != 'true' }}


    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID_DEV }}:role/GitHubActions-Infrastructure-${{ env.ENVIRONMENT }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Fetch IPA Credentials
        run: |
          IPA_ADMIN_PASS=$(aws secretsmanager get-secret-value \
            --secret-id dev/freeipa/admin-password \
            --query SecretString --output text)
          
          echo "::add-mask::${IPA_ADMIN_PASS}"
          echo "IPA_ADMIN_PASSWORD=${IPA_ADMIN_PASS}" >> $GITHUB_ENV


          IPA_LDAP_PASS=$(aws secretsmanager get-secret-value \
            --secret-id dev/freeipa/dm-password \
            --query SecretString --output text)
          
          echo "::add-mask::${IPA_LDAP_PASS}"
          echo "IPA_DM_PASSWORD=${IPA_LDAP_PASS}" >> $GITHUB_ENV


      - name: Pull latest code
        run: |
          sudo ssh root@10.0.63.10 "cd /srv/repo/ && git pull origin dev"

      - name: Run FreeIPA playbook
        run: |
           sudo ssh root@10.0.63.10 "\
              export IPA_ADMIN_PASSWORD='${{ env.IPA_ADMIN_PASSWORD }}' && \
              export IPA_DM_PASSWORD='${{ env.IPA_DM_PASSWORD }}' && \
              cd /srv/repo/ansible/dev/ && \
              ansible-playbook -i inventory/inventory.ini playbooks/freeipa/freeipa_setup.yml"