name: "[DEV] Ping Test"
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      # - 'terraform/dev/proxmox/lxc/local_runner/**'
      # - 'ansible/dev/playbooks/local-runner/setup_tools.yml'
      - '.github/workflows/ping-test.yml'

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: dev
  # TF_WORKING_DIR: terraform/dev/proxmox/lxc/local_runner

jobs: 

  test-dev:
    name: "Test Ping Dev"
    runs-on: dev-local-runner

    steps:

      - name: Run Ping Test
        run: |
              ssh -o StrictHostKeyChecking=no root@10.0.63.10 "
                ping -c 4 172.16.65.197;
                ping -c 4 10.0.62.10
                ping -c 4 10.0.63.1"

  test-prod:
    name: "Test Ping Prod"
    runs-on: prod-local-runner

    steps:

      - name: Run Ping Test
        run: |
              ssh -o StrictHostKeyChecking=no root@10.0.53.10 "
                ping -c 4 172.17.65.73;
                ping -c 4 10.0.52.10
                ping -c 4 10.0.53.1"
